### ISSUE TITLE
Splashes are centered on blocks

### ISSUE THREAD

**Issue by SPINZ1** [Ladysnake/Effective#243] opened 2024-03-03 22:23 UTC
When the mod was on fabric, splashes appeared exactly where entities landed:

https://github.com/Ladysnake/Effective/assets/145732023/9cd8323f-9c94-4a5f-b72a-bfb47e21b410

Now, on quilt, the splashes are locked to the block grid:

https://github.com/Ladysnake/Effective/assets/145732023/7bd4984c-be4a-482c-a9d0-44084d74355b

**Comment by DarksideAlex** [comment] 2024-04-25 12:24
Note to devs: It seems like the problem is not with the water splash function itself, but rather the input values.

**Comment by DarksideAlex** [comment] 2024-04-25 12:34
Update: I got a feeling that it has to do with quilts entity.getX() and entity.getY() outputs. They are supposed to be doubles, but it's the only reasonable cause to me at the moment.

**Comment by doctor4t** [comment] 2024-09-19 20:11
Fixed in latest

**Closed by doctor4t** 2024-09-19 20:11 UTC
