### ISSUE TITLE
Black Splashes

### ISSUE THREAD

**Issue by JustAHuman-xD** [Ladysnake/Effective#12] opened 2021-12-15 23:41 UTC
The splashes are completely black and not 3D, and most mobs won’t even activate the splashes, lava splashes work fine. I know there are other issues with this in it but I wanted to make it its own issues, and this uses different mods then them.

Mods using:
![C7EA0E2F-183E-467F-A5DF-777DF9566921](https://user-images.githubusercontent.com/65748158/146281810-c1516c21-f044-4d6a-8e94-75354cc8f9ae.jpeg)

**Comment by Sollace** [comment] 2021-12-16 14:53
This appears to be a duplicate of #5 (both are caused by Sodium)

Please use the search function to check whether the issue you're having has been reported before creating a new one.

**Comment by Fusion-Flux** [comment] 2021-12-16 15:25
After some testing it appears this bug also happens with Illuminations installed

**Comment by nikolayVR06** [comment] 2021-12-20 18:46
it works without illuminations

**Closed** 2022-08-27 15:34 UTC
