### ISSUE TITLE
Black Splash Textures and no Cascades

### ISSUE THREAD

**Issue by Matimax1** [Ladysnake/Effective#7] opened 2021-12-15 21:32 UTC
Splashes appear black and there is no cascade visual and sound effects, only droplet particles

![2021-12-15_15 58 16](https://user-images.githubusercontent.com/96208533/146267600-b3864227-66c6-4178-b4f0-3b13c4b5b25c.png)
![2021-12-15_16 20 19](https://user-images.githubusercontent.com/96208533/146267615-e7a3e374-f88a-473b-ae59-75175d23bfb6.png)
Here is my Mods List:
![image](https://user-images.githubusercontent.com/96208533/146268145-88518910-700c-48d4-a6a3-0bbca0d5aecd.png)

**Comment by Sollace** [comment] 2021-12-15 21:52
This appears to be a duplicate of #5 (both are caused by Sodium)

**Comment by Matimax1** [comment] 2021-12-15 21:56
> This appears to be a duplicate of #5 (both are caused by Sodium)

I tried removing both Sodium and Iris. That solved the cascades, but the splashes were still black.

**Comment by MrBsCool** [comment] 2022-01-14 20:46
I have the same issue. However, it is not because of Sodium or Iris. When I run Effective with no other mods on my iMac the splashes are black. They remained black until I used Iris and Sodium with shaders and then they appeared normal. But when I use a windows setup, the splashes appear normal without using shaders. I have no idea what is going on and I would appreciate some insight because I really like this mod and do not want to have to get rid of it.

**Closed** 2022-08-27 15:34 UTC
