### ISSUE TITLE
Rain Ripples on Undergound Water

### ISSUE THREAD

**Issue by SurealSulwyn** [Ladysnake/Effective#117] opened 2022-09-15 00:08 UTC
Installation:
- Minecraft: v1.19.2
- Fabric Loader: v0.14.9
- Effective: v1.3
- Fabric API: v0.60.0+1.19.2
- Mod Menu: v4.0.6

Expected Behaviour:
- Rain ripples appear on source water that has sky access when it is raining

Actual Behaviour:
- Rain ripples appear on all source water when it is raining, even underground water with no sky access

**Comment by lonefelidae16** [comment] 2022-09-15 21:57
Can confirm, it is caused by `WaterFluidMixin.shouldRippile`.

Using `World#hasRain(BlockPos)` instead of `World#isRaining() && BlockState#isAir()` on line 40 would fix this issue.

https://github.com/Ladysnake/Effective/blob/9016afe9a9126a5052e1431405a74f91aecc2ead/src/main/java/ladysnake/effective/mixin/WaterFluidMixin.java#L36-L43

**Comment by doctor4t** [comment] 2022-11-17 10:35
Thanks for the fix lonefelidae, didn't even know that method was a thing! Appreciate it a lot <3

**Comment by doctor4t** [comment] 2022-11-17 10:57
After giving it a try, it seems hasRain doesn't work on the client, as isSkyVisible always returns false on the client for some reason

**Comment by lonefelidae16** [comment] 2022-11-18 11:31
Thank you for trying my patch!

> After giving it a try, it seems hasRain doesn't work on the client, as isSkyVisible always returns false on the client for some reason

I wonder why. I installed and tried Quilt immediately and it worked fine.

![2022-11-18_20 13 51](https://user-images.githubusercontent.com/74746227/202694231-276bacca-b66e-45f0-8ba1-a79780b70654.png)

My WaterFluidMixin.java is:

```diff
	@Unique
	private static boolean shouldRipple(World world, BlockPos pos) {
		if (EffectiveConfig.rainRippleDensity > 0) {
			FluidState fluidState = world.getFluidState(pos);
-			return fluidState.isSource() && world.isRaining() && world.getBlockState(pos.add(0, 1, 0)).isAir();
+			return fluidState.isSource() && world.hasRain(pos.up());
		}
		return false;
	}
```

It is important to note that it must to be specified the position of the Y-axis +1 to work, rather than entering `pos` directly.

**Comment by doctor4t** [comment] 2022-11-18 11:39
Oh, i tried has rain on the POS itself, not pos.up, my bad. Alright I'll
try it out again!

Le ven. 18 nov. 2022, 12:31, lonefelidae16 ***@***.***> a
écrit :

**Comment by Arathain** [comment] 2023-01-05 09:40
Fixed on latest release.

**Closed by Arathain** 2023-01-05 09:40 UTC
