### ISSUE TITLE
Splash not working when water is 1 block deep

### ISSUE THREAD

**Issue by DerpDerpling** [Ladysnake/Effective#34] opened 2021-12-25 21:32 UTC
heres an example

https://user-images.githubusercontent.com/57187871/147393909-1b77ad7c-75cb-460f-a305-2420d019dcc6.mp4

**Comment by doctor4t** [comment] 2021-12-25 21:44
Splash height depends on the speed you have once you are in the water. If the water isn't deep enough, your speed will be reduced to zero. To fix this, I would need to have the mod both serverside and clientside, which isn't something I want, so I won't fix this.

Works as intended

**Closed by doctor4t** 2021-12-25 21:44 UTC
