### ISSUE TITLE
Random crash

### ISSUE THREAD

**Issue by Xyur1** [Ladysnake/Effective#103] opened 2022-07-13 21:34 UTC
When i try to use the mod, the game don't opens and says "error code -1".

**Comment by JKaiya** [comment] 2022-07-15 10:25
Did you try isolating the mod to see if this mod is the problem? When downloading a new set of mods it is common for some to be bugged and cause crashes. Make sure you check the dependencies to see if you got all the necessary mods too.

**Comment by mergelong** [comment] 2022-09-30 23:21
I'm having a similar issue. I am running quite a few other mods, but v1.22 seems to work, whereas 1.3 crashes. MidnightLib has been added. The error message reads:

```
Uncaught exception in thread "main"
java.lang.RuntimeException: Failed to read accessWidener file from mod effective
	at net.fabricmc.loader.impl.FabricLoaderImpl.loadAccessWideners(FabricLoaderImpl.java:441)
	at net.fabricmc.loader.impl.launch.knot.Knot.init(Knot.java:151)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:68)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
Caused by: net.fabricmc.accesswidener.AccessWidenerFormatException: line 1: Namespace (named) does not match current runtime namespace (intermediary)
	at net.fabricmc.accesswidener.AccessWidenerReader.error(AccessWidenerReader.java:285)
	at net.fabricmc.accesswidener.AccessWidenerReader.read(AccessWidenerReader.java:84)
	at net.fabricmc.loader.impl.FabricLoaderImpl.loadAccessWideners(FabricLoaderImpl.java:439)
	... 3 more

```

**Comment by lonefelidae16** [comment] 2022-10-01 05:04
> I'm having a similar issue. I am running quite a few other mods, but v1.22 seems to work, whereas 1.3 crashes. MidnightLib has been added. The error message reads:
> 
> ```
> Uncaught exception in thread "main"
> java.lang.RuntimeException: Failed to read accessWidener file from mod effective
> 	at net.fabricmc.loader.impl.FabricLoaderImpl.loadAccessWideners(FabricLoaderImpl.java:441)
> 	at net.fabricmc.loader.impl.launch.knot.Knot.init(Knot.java:151)
> 	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:68)
> 	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
> Caused by: net.fabricmc.accesswidener.AccessWidenerFormatException: line 1: Namespace (named) does not match current runtime namespace (intermediary)
> 	at net.fabricmc.accesswidener.AccessWidenerReader.error(AccessWidenerReader.java:285)
> 	at net.fabricmc.accesswidener.AccessWidenerReader.read(AccessWidenerReader.java:84)
> 	at net.fabricmc.loader.impl.FabricLoaderImpl.loadAccessWideners(FabricLoaderImpl.java:439)
> 	... 3 more
> ```

The same issue seems to be happening with other mods. https://www.curseforge.com/minecraft/mc-mods/fabric-shield-lib?comment=16

Please try to use latest Fabric Loader. Effective 1.3 has been compiled with Fabric Loader 0.14.9.

**Comment by mergelong** [comment] 2022-10-01 16:05
>
> The same issue seems to be happening with other mods. https://www.curseforge.com/minecraft/mc-mods/fabric-shield-lib?comment=16
> 
> Please try to use latest Fabric Loader. Effective 1.3 has been compiled with Fabric Loader 0.14.9.

I am already running 0.14.9. Are there any known incompatibilities with popular optimization mods such as Sodium, Lithium, Indium, etc?

**Comment by lonefelidae16** [comment] 2022-10-01 23:41
> I am already running 0.14.9. Are there any known incompatibilities with popular optimization mods such as Sodium, Lithium, Indium, etc?

I’m not sure about those incompatibilities. My instance works well with Indium, Lithium, and other 85 mods. Here is my modlist:
[latest.log](https://github.com/Ladysnake/Effective/files/9691254/latest.log)

It seems a bit late to get some logs in `AccessWidenerReader#read` using `Mixin` annotation from mod, so I tried to place codes directly, but Fabric replaced my custom jar with the original one.
I can’t seem to reproduce this issue in my environment, sorry.

**Comment by mergelong** [comment] 2022-10-02 18:05
The issue has persisted even after I pared down my mod list to just Effective, MidnightLib, Modmenu, Sodium, and Fabric API, all of which should be their newest versions, as well as Fabric Loader 0.14.9. Here is my modlist as well as the crash report: 
[latest.log](https://github.com/Ladysnake/Effective/files/9693152/latest.log)

**Comment by lonefelidae16** [comment] 2022-10-03 00:23
> The issue has persisted even after I pared down my mod list to just Effective, MidnightLib, Modmenu, Sodium, and Fabric API, all of which should be their newest versions, as well as Fabric Loader 0.14.9. Here is my modlist as well as the crash report: [latest.log](https://github.com/Ladysnake/Effective/files/9693152/latest.log)

Weird... Effective’s version string in your log shows `${version}` which should be `1.3`. I downloaded once again from CurseForge to match your mods, but Minecraft launched normally. CurseForge has md5sum hash for each files, so I think it would be better to check your Effective hash value after downloading.

**Comment by mergelong** [comment] 2022-10-03 01:29
Ah, I got it. I had accidentally downloaded the sources file from here on Github like an idiot instead of the mod itself. It works just fine now, thank you for your help.

**Comment by Arathain** [comment] 2023-01-05 09:43
Fixed on latest release(s).

**Closed by Arathain** 2023-01-05 09:43 UTC
