### ISSUE TITLE
Underwater Waterfalls? 

### ISSUE THREAD

**Issue by juicebin** [Ladysnake/Effective#26] opened 2021-12-17 23:08 UTC
Normal waterfalls work fine. However I came across an _underwater_ waterfall...

![2021-12-17_17 56 37](https://user-images.githubusercontent.com/80006649/146617733-209d8d2e-d988-4933-95b5-869eed57acd9.png)

Here are the other mods I have, just in case! They're all client-side.
- Blur by Motschen
- Chat Head by dzwdz
- Cloth Config API by shedaniel
- Dynamic Sound Filters by andre111_
- Eating Animation by theone_ss
- ExtraSounds by stashymane
- Illuminations by doctor4t
- Ok Zoomer by EnnuiLangeweile
- Visuality by PinkGoosik

**Comment by Sollace** [comment] 2021-12-18 11:43
Duplicate of #2

**Closed** 2021-12-25 21:48 UTC
