### ISSUE TITLE
Black Splashes With Illuminations

### ISSUE THREAD

**Issue by Fusion-Flux** [Ladysnake/Effective#18] opened 2021-12-16 15:34 UTC
The black splashes bug happens with Illuminations installed

**Comment by doctor4t** [comment] 2021-12-16 15:36
Yo the author of Illuminations dumb as fuck for real

**Comment by Fusion-Flux** [comment] 2021-12-16 15:37
sghejlkehnvguoiaryhguoi

**Comment by Slymeball** [comment] 2021-12-19 21:31
I would like to add on saying that I do not have any other docter4t mods installed but I still have the same issue. Running Ubuntu 20.04 on iMac Late 2014

**Comment by nikolayVR06** [comment] 2021-12-20 18:35
> Yo the author of Illuminations dumb as fuck for real

it still not working without illuminations

**Comment by MarkinhosMLP** [comment] 2021-12-27 02:14
up

**Comment by JustAHuman-xD** [comment] 2021-12-29 04:15
Just want to note that all my splashes were black but then when i used shaders they were fixed!!
Just want to note that!

**Comment by MarkinhosMLP** [comment] 2021-12-31 18:56
up

**Comment by JustAHuman-xD** [comment] 2022-01-01 18:33
So you guys know: !!!The black splashes appears to be a computer hardware problem. I used identical mods and video settings on my laptop and pc and on my laptop the splashes were black. But on my PC they were not!!!

**Comment by MarkinhosMLP** [comment] 2022-01-01 20:19
nope, its not a hardware problem, its from the mod itself, an example is if you remove some mods like sodium, illuminations and others they will work again, and also, if you apply any shaders it will return back, but if you dont use shaders and use these mods than it will be black

**Comment by JustAHuman-xD** [comment] 2022-01-02 07:06
Then I wonder why that happened to me

**Comment by MarkinhosMLP** [comment] 2022-01-04 22:26
wondering if it will be fixed... i miss the water splashes

**Comment by MarkinhosMLP** [comment] 2022-06-05 08:54
> wondering if it will be fixed... i miss the water splashes

hey bro its me from the future 6 months later, we still miss the water splashes

**Comment by Slymeball** [comment] 2022-06-05 13:45
Same, I still use Effective and I'm waiting for a fix.


________________________________

**Comment by WildTom1** [comment] 2022-06-10 00:28
I have the same issue, I use sodium; also, I'm on Linux.

**Comment by lonefelidae16** [comment] 2022-06-16 04:12
Finally I could catch this issue so I would report about it.

First of all: **PLEASE DESCRIBE** Your Hardware and Environment.

To reproduce this issue: use Intel MESA Driver on Linux with Discrete GPU (My Laptop is Ubuntu 22.04 Jammy running on ASUS UX303UB)
![2022-06-16_11 57 08](https://user-images.githubusercontent.com/74746227/173986164-c14dc003-d853-423b-9824-219199ce0a65.png)

It is also 'Black' splashes using shaderpack (tested with Sildur’s Vibrant Shaders v1.32 Lite):
![2022-06-16_11 57 39](https://user-images.githubusercontent.com/74746227/173986357-56309cf1-75cd-438b-b5f7-d9234edd2664.png)

The reason this issue has not been realized so far is that I have been using NVIDIA Drivers all along:
![2022-06-16_12 33 28](https://user-images.githubusercontent.com/74746227/173986924-e4438e88-30e6-4681-9a7f-c6073ac1a4d9.png)

It also works fine with AMD Drivers (but it’s on Windows 11):
![2022-06-08_22 15 19](https://user-images.githubusercontent.com/74746227/173987593-88688352-c1ea-4c52-8845-72b2f64ebd53.png)

However, I don’t have any AMD APU so I can’t test with AMD’s internal GPU.

So, the workaround is:
* Are you using Intel MESA Driver or internal GPU? Please try another external GPU.

This issue can be resolved when:
* Make internal GPU Driver compatible.

**Closed** 2022-08-27 15:34 UTC
Labels: bug
