### ISSUE TITLE
Splashes appear as entirely black using Sodium and Iris

### ISSUE THREAD

**Issue by samulation2** [Ladysnake/Effective#6] opened 2021-12-15 21:29 UTC
Large splashes from players and entities appear as transparent/black, no matter the graphics settings.

**Comment by AViewFromTheTop** [comment] 2021-12-15 21:32
I'm using both Sodium and Iris and I don't have this issue.

**Comment by Sollace** [comment] 2021-12-15 21:53
This appears to be a duplicate of #5 (both are caused by Sodium)

**Comment by MadlyBrain** [comment] 2021-12-15 22:10
Cascades not showing is a problem with sodium, but the splashes that are completely black still happen even if the only mods in the mod folder is this mod itself and fabric api so it actually loads.

**Comment by DWW256** [comment] 2021-12-15 23:04
I am observing this bug on Linux with no mods installed besides Effective and the Fabric API.

**Comment by DarianLStephens** [comment] 2021-12-16 01:29
I don't have black splashes, I just don't see splashes at all.
Even dropping a Ravager from 200 blocks up gives nothing, just the spray of white particles.

**Comment by Athos117** [comment] 2021-12-16 03:50
I am having the black splashes issue too. I tried it with Effective and Fabric API only, 1.18.1 on Windows 10. Gif showing the issue: [https://imgur.com/a/nYZ6iP6](https://imgur.com/a/nYZ6iP6)

Also, #7 and #12 should merge to this thread.

**Comment by JustAHuman-xD** [comment] 2021-12-26 19:13
I have the same issue as everyone here, all splashes are appearing as black, I'm going to do some digging to try and figure out the cause.

**Comment by bastiannunezb** [comment] 2022-01-07 22:58
I don't think it's Sodium's fault — I'm having the same issue in Linux using Fabric 0.12.12 with no additional mods other than the Fabric API (latest version). The Forge version seems to work fine.

**Closed** 2022-08-27 15:34 UTC
