### ISSUE TITLE
Versions above 1.4 won't show up in Mod Menu mod on fabric

### ISSUE THREAD

**Issue by le0-VV** [Ladysnake/Effective#155] opened 2022-12-11 03:23 UTC
Any version above 1.4 for fabric will not show up in mod menu and wont show up in gameplay either, 1.4 works fine. Tested as the only mod and with fabric api & mod menu

**Comment by Arathain** [comment] 2022-12-11 09:10
Duplicate of #134.

**Closed by Arathain** 2022-12-11 09:10 UTC
